### PR TITLE
Add offline site support

### PR DESCRIPTION
**Pull request by c-git**
# Disclaimer

I know this doesn't quite match the intent of this theme but I decided to open the pull request in case you were interested in adding it. 

# Rational and use case

I use one of my sites as an offline documentation tool for me to record things I don't want to lookup again and it needs to work even when I don't have a network connection. I'd been using it for a while and got fed up of always needing to click on index.html after I click on the page I want. So I opened a [topic](https://zola.discourse.group/t/create-offline-website/1374) on the zola discourse to get help and got pointed to a the abridge them as they have a solution and while it's not perfect it's will fix my problem most of the time. Especially when I use the navigation menu on the left or the "default" table of contents on the empty index homepage. So I've implemented it in this theme because I prefer this theme for my use case.

# Documentation Update

If you do decide to add it I was wondering if I should try to document the features that have been added to readme.md? Happy to iterate on the documentation update until you're happy with it because I understand that's the first interaction a user has with the theme. Mostly because I'm not sure if there are other people who have a similar use case to mine who would benefit from not needing to reinvent the wheel.

Features that I am considering documenting (let me know if I missed any or if you would prefer leave any out):
- Offline site support
- Default landing page with table of contents
- Always clickable logo
- Missing logo shows page title in it's place
- Logo and favicon co-located file support (doesn't need to be a fully qualified url)
- Specific steps to take to add the theme as a submodule (would allow users easily benefit from any updates) NB: not replace current install instructions just provide an alternate method
- Create a demo site showing the table of content feature

### CODE REVIEW

**Comment by c-git** [comment]
It just came to my attention that this does not work well with `zola serve`. Works fine for offline with `zola build` but when it is enabled `zola serve` it doesn't load the css or page content.

**Comment by codeandmedia** [comment]
Thanks! Let me think about it a bit.

**Comment by c-git** [comment]
Yep fair enough, let me know if you want me to do anything further in the meanwhile.

**Comment by c-git** [comment]
Was refactoring the code to move the duplicated code into a separate page that I could use include to bring into context then realized that it was already in the context of all the pages as all pages extend from index.html and thus the code I was about to pull out was just duplicated so I removed the duplicated ones and left it in index.html

**Comment by codeandmedia** [comment]
thanks! I don't see any issues with backward compatibility, additional option is totally file in config file. It could be really good use-case and I'll be happy to add your explanation to readme.md

**Comment by c-git** [comment]
Ok thanks, will try to write it up and submit a PR. Are you also ok with the alternate install instructions (using a sub-module)?

**Comment by codeandmedia** [comment]
sure, I remember Vincent, Zola Creator, prefers submodules, but it's a bit more complex for newbies so I decided to use trivial copy&paste, but submodule more in a fit to Zola-way

**Comment by c-git** [comment]
I just want to provide an alternative option. It has a distinct advantage that it makes it easy to update the theme if changes are made to this repo. (Not replace the copy paste option).

**Comment by c-git** [comment]
Hi @codeandmedia  I have what I think is quick questions for you. I'm going to make a small fix to prevent the issues with `ugly_url` when used with `zola serve`. I haven't had a chance to do the updated docs yet. I'm trying to decide between waiting to create a pull request after I've also done the docs or submit the small pull request for the `zola serve` fix separately. Would you prefer I do a small pull request with the fix first?

**Comment by codeandmedia** [comment]
hi @c-git fast fix is always better

**Pull request merged**
